version: "3.9"

services:
  forticlient:
    build:
      context: .
      dockerfile: Dockerfile
    image: hybirdcorp/docker-forticlient
    restart: unless-stopped
    environment:
      - VPNADDR=${VPNADDR}
      - VPNUSER=${VPNUSER}
      - VPNPASS=${VPNPASS}
      - VPNTIMEOUT=${VPNTIMEOUT:-10}
    ports:
      - "3000:3000"
      - "3001:3001"
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.rp_filter=2
    dns:
      - 8.8.8.8
      - 8.8.4.4

  filezilla:
    image: lscr.io/linuxserver/filezilla:latest
    container_name: filezilla
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
      - ./app:/app
    restart: unless-stopped
    network_mode: "service:forticlient"
    depends_on:
      - forticlient